### ISSUE TITLE
SQLCMD18 encryption issue

### ISSUE THREAD

**Issue by Belorus** [jonathanpotts/docker-babelfishpg#6]
Hi Jonathan,
Thank you for the docker image!

I tried to run our SQL schema deployment pipeline against babelfishpg and got following error:

Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Encryption not supported on SQL Server..
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Client unable to establish connection.

SQLCMD18 by default enables encryption that can't be disabled (only trust to self-signed certificate can be enabled).

SQLCMD17 works like a charm.

I asked in babelfishpg repo - https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/891 and it seems that babelfish itself supports encryption, just it should be enabled during compilation

**Comment by jonathanpotts** [comment]
I've updated the `jonathanpotts/babelfishpg` images on Docker Hub with tags `latest` and `2.3.0` to have SSL support built in. It will need to be configured after starting up the container due to it needing an SSL certificate. For more information, go to: https://www.postgresql.org/docs/14/ssl-tcp.html

For example, I ran the following commands in the container's terminal to configure SSL:

```sh
cd /data/babelfish
openssl req -new -x509 -days 365 -nodes -text -out server.crt -keyout server.key -subj "/CN=localhost"
chmod og-rwx server.key
echo "ssl = on" >> postgresql.conf
```

I then restarted the container and then received this output from `sqlcmd` using Encryption (with the `-N -C` arguments).

```pwsh
PS C:\Users\jonat> sqlcmd -N -C -S localhost -U babelfish_user -P 12345678
1> SELECT @@VERSION
2> GO
version                                                                                                                 

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Babelfish for PostgreSQL with SQL Server Compatibility - 12.0.2000.8
Mar  4 2023 17:30:26
Copyright (c) Amazon Web Services
PostgreSQL 14.6 on x86_64-pc-linux-gnu (Babelfish 2.3.0)


(1 rows affected)
1>
```

**Comment by Belorus** [comment]
Thank you! Works like a charm
